// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"
	models "gobooru/internal/models"

	mock "github.com/stretchr/testify/mock"

	repositories "gobooru/internal/repositories"
)

// MockPostNotesRepository is an autogenerated mock type for the PostNotesRepository type
type MockPostNotesRepository struct {
	mock.Mock
}

type MockPostNotesRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostNotesRepository) EXPECT() *MockPostNotesRepository_Expecter {
	return &MockPostNotesRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, args
func (_m *MockPostNotesRepository) Create(ctx context.Context, args repositories.CreatePostNotesArgs) (models.PostNote, error) {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.PostNote
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repositories.CreatePostNotesArgs) (models.PostNote, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repositories.CreatePostNotesArgs) models.PostNote); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(models.PostNote)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repositories.CreatePostNotesArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostNotesRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPostNotesRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - args repositories.CreatePostNotesArgs
func (_e *MockPostNotesRepository_Expecter) Create(ctx interface{}, args interface{}) *MockPostNotesRepository_Create_Call {
	return &MockPostNotesRepository_Create_Call{Call: _e.mock.On("Create", ctx, args)}
}

func (_c *MockPostNotesRepository_Create_Call) Run(run func(ctx context.Context, args repositories.CreatePostNotesArgs)) *MockPostNotesRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repositories.CreatePostNotesArgs))
	})
	return _c
}

func (_c *MockPostNotesRepository_Create_Call) Return(_a0 models.PostNote, _a1 error) *MockPostNotesRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostNotesRepository_Create_Call) RunAndReturn(run func(context.Context, repositories.CreatePostNotesArgs) (models.PostNote, error)) *MockPostNotesRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPostNotesRepository creates a new instance of MockPostNotesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostNotesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostNotesRepository {
	mock := &MockPostNotesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
