// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"

	sqlx "github.com/go-sqlx/sqlx"
)

// MockDBClient is an autogenerated mock type for the DBClient type
type MockDBClient struct {
	mock.Mock
}

type MockDBClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDBClient) EXPECT() *MockDBClient_Expecter {
	return &MockDBClient_Expecter{mock: &_m.Mock}
}

// ExecContext provides a mock function with given fields: ctx, query, args
func (_m *MockDBClient) ExecContext(ctx context.Context, query string, args ...interface{}) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (sql.Result, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) sql.Result); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDBClient_ExecContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContext'
type MockDBClient_ExecContext_Call struct {
	*mock.Call
}

// ExecContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...interface{}
func (_e *MockDBClient_Expecter) ExecContext(ctx interface{}, query interface{}, args ...interface{}) *MockDBClient_ExecContext_Call {
	return &MockDBClient_ExecContext_Call{Call: _e.mock.On("ExecContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockDBClient_ExecContext_Call) Run(run func(ctx context.Context, query string, args ...interface{})) *MockDBClient_ExecContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockDBClient_ExecContext_Call) Return(_a0 sql.Result, _a1 error) *MockDBClient_ExecContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDBClient_ExecContext_Call) RunAndReturn(run func(context.Context, string, ...interface{}) (sql.Result, error)) *MockDBClient_ExecContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetContext provides a mock function with given fields: ctx, dest, query, args
func (_m *MockDBClient) GetContext(ctx context.Context, dest interface{}, query string, args ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, dest, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, string, ...interface{}) error); ok {
		r0 = rf(ctx, dest, query, args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDBClient_GetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContext'
type MockDBClient_GetContext_Call struct {
	*mock.Call
}

// GetContext is a helper method to define mock.On call
//   - ctx context.Context
//   - dest interface{}
//   - query string
//   - args ...interface{}
func (_e *MockDBClient_Expecter) GetContext(ctx interface{}, dest interface{}, query interface{}, args ...interface{}) *MockDBClient_GetContext_Call {
	return &MockDBClient_GetContext_Call{Call: _e.mock.On("GetContext",
		append([]interface{}{ctx, dest, query}, args...)...)}
}

func (_c *MockDBClient_GetContext_Call) Run(run func(ctx context.Context, dest interface{}, query string, args ...interface{})) *MockDBClient_GetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(interface{}), args[2].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockDBClient_GetContext_Call) Return(_a0 error) *MockDBClient_GetContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDBClient_GetContext_Call) RunAndReturn(run func(context.Context, interface{}, string, ...interface{}) error) *MockDBClient_GetContext_Call {
	_c.Call.Return(run)
	return _c
}

// NamedExecContext provides a mock function with given fields: ctx, query, arg
func (_m *MockDBClient) NamedExecContext(ctx context.Context, query string, arg interface{}) (sql.Result, error) {
	ret := _m.Called(ctx, query, arg)

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) (sql.Result, error)); ok {
		return rf(ctx, query, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) sql.Result); ok {
		r0 = rf(ctx, query, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, interface{}) error); ok {
		r1 = rf(ctx, query, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDBClient_NamedExecContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NamedExecContext'
type MockDBClient_NamedExecContext_Call struct {
	*mock.Call
}

// NamedExecContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - arg interface{}
func (_e *MockDBClient_Expecter) NamedExecContext(ctx interface{}, query interface{}, arg interface{}) *MockDBClient_NamedExecContext_Call {
	return &MockDBClient_NamedExecContext_Call{Call: _e.mock.On("NamedExecContext", ctx, query, arg)}
}

func (_c *MockDBClient_NamedExecContext_Call) Run(run func(ctx context.Context, query string, arg interface{})) *MockDBClient_NamedExecContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MockDBClient_NamedExecContext_Call) Return(_a0 sql.Result, _a1 error) *MockDBClient_NamedExecContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDBClient_NamedExecContext_Call) RunAndReturn(run func(context.Context, string, interface{}) (sql.Result, error)) *MockDBClient_NamedExecContext_Call {
	_c.Call.Return(run)
	return _c
}

// NamedQueryContext provides a mock function with given fields: ctx, query, arg
func (_m *MockDBClient) NamedQueryContext(ctx context.Context, query string, arg interface{}) (*sqlx.Rows, error) {
	ret := _m.Called(ctx, query, arg)

	var r0 *sqlx.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) (*sqlx.Rows, error)); ok {
		return rf(ctx, query, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) *sqlx.Rows); ok {
		r0 = rf(ctx, query, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlx.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, interface{}) error); ok {
		r1 = rf(ctx, query, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDBClient_NamedQueryContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NamedQueryContext'
type MockDBClient_NamedQueryContext_Call struct {
	*mock.Call
}

// NamedQueryContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - arg interface{}
func (_e *MockDBClient_Expecter) NamedQueryContext(ctx interface{}, query interface{}, arg interface{}) *MockDBClient_NamedQueryContext_Call {
	return &MockDBClient_NamedQueryContext_Call{Call: _e.mock.On("NamedQueryContext", ctx, query, arg)}
}

func (_c *MockDBClient_NamedQueryContext_Call) Run(run func(ctx context.Context, query string, arg interface{})) *MockDBClient_NamedQueryContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MockDBClient_NamedQueryContext_Call) Return(_a0 *sqlx.Rows, _a1 error) *MockDBClient_NamedQueryContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDBClient_NamedQueryContext_Call) RunAndReturn(run func(context.Context, string, interface{}) (*sqlx.Rows, error)) *MockDBClient_NamedQueryContext_Call {
	_c.Call.Return(run)
	return _c
}

// SelectContext provides a mock function with given fields: ctx, dest, query, args
func (_m *MockDBClient) SelectContext(ctx context.Context, dest interface{}, query string, args ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, dest, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, string, ...interface{}) error); ok {
		r0 = rf(ctx, dest, query, args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDBClient_SelectContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectContext'
type MockDBClient_SelectContext_Call struct {
	*mock.Call
}

// SelectContext is a helper method to define mock.On call
//   - ctx context.Context
//   - dest interface{}
//   - query string
//   - args ...interface{}
func (_e *MockDBClient_Expecter) SelectContext(ctx interface{}, dest interface{}, query interface{}, args ...interface{}) *MockDBClient_SelectContext_Call {
	return &MockDBClient_SelectContext_Call{Call: _e.mock.On("SelectContext",
		append([]interface{}{ctx, dest, query}, args...)...)}
}

func (_c *MockDBClient_SelectContext_Call) Run(run func(ctx context.Context, dest interface{}, query string, args ...interface{})) *MockDBClient_SelectContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(interface{}), args[2].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockDBClient_SelectContext_Call) Return(_a0 error) *MockDBClient_SelectContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDBClient_SelectContext_Call) RunAndReturn(run func(context.Context, interface{}, string, ...interface{}) error) *MockDBClient_SelectContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDBClient creates a new instance of MockDBClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDBClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDBClient {
	mock := &MockDBClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
