// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// MockTagCategoryController is an autogenerated mock type for the TagCategoryController type
type MockTagCategoryController struct {
	mock.Mock
}

type MockTagCategoryController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagCategoryController) EXPECT() *MockTagCategoryController_Expecter {
	return &MockTagCategoryController_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: c
func (_m *MockTagCategoryController) List(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTagCategoryController_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTagCategoryController_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - c echo.Context
func (_e *MockTagCategoryController_Expecter) List(c interface{}) *MockTagCategoryController_List_Call {
	return &MockTagCategoryController_List_Call{Call: _e.mock.On("List", c)}
}

func (_c *MockTagCategoryController_List_Call) Run(run func(c echo.Context)) *MockTagCategoryController_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *MockTagCategoryController_List_Call) Return(_a0 error) *MockTagCategoryController_List_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTagCategoryController_List_Call) RunAndReturn(run func(echo.Context) error) *MockTagCategoryController_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTagCategoryController creates a new instance of MockTagCategoryController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagCategoryController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagCategoryController {
	mock := &MockTagCategoryController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
