// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"
	models "gobooru/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockTagCategoryRepository is an autogenerated mock type for the TagCategoryRepository type
type MockTagCategoryRepository struct {
	mock.Mock
}

type MockTagCategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagCategoryRepository) EXPECT() *MockTagCategoryRepository_Expecter {
	return &MockTagCategoryRepository_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: ctx
func (_m *MockTagCategoryRepository) List(ctx context.Context) ([]models.TagCategory, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.TagCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.TagCategory, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.TagCategory); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TagCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTagCategoryRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTagCategoryRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTagCategoryRepository_Expecter) List(ctx interface{}) *MockTagCategoryRepository_List_Call {
	return &MockTagCategoryRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockTagCategoryRepository_List_Call) Run(run func(ctx context.Context)) *MockTagCategoryRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTagCategoryRepository_List_Call) Return(_a0 []models.TagCategory, _a1 error) *MockTagCategoryRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTagCategoryRepository_List_Call) RunAndReturn(run func(context.Context) ([]models.TagCategory, error)) *MockTagCategoryRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTagCategoryRepository creates a new instance of MockTagCategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagCategoryRepository {
	mock := &MockTagCategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
