// Code generated by mockery v2.37.1. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// MockHealthCheckController is an autogenerated mock type for the HealthCheckController type
type MockHealthCheckController struct {
	mock.Mock
}

type MockHealthCheckController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthCheckController) EXPECT() *MockHealthCheckController_Expecter {
	return &MockHealthCheckController_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function with given fields: c
func (_m *MockHealthCheckController) Ping(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHealthCheckController_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockHealthCheckController_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - c echo.Context
func (_e *MockHealthCheckController_Expecter) Ping(c interface{}) *MockHealthCheckController_Ping_Call {
	return &MockHealthCheckController_Ping_Call{Call: _e.mock.On("Ping", c)}
}

func (_c *MockHealthCheckController_Ping_Call) Run(run func(c echo.Context)) *MockHealthCheckController_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *MockHealthCheckController_Ping_Call) Return(_a0 error) *MockHealthCheckController_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthCheckController_Ping_Call) RunAndReturn(run func(echo.Context) error) *MockHealthCheckController_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHealthCheckController creates a new instance of MockHealthCheckController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthCheckController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthCheckController {
	mock := &MockHealthCheckController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
