// Code generated by mockery v2.37.1. DO NOT EDIT.

package mocks

import (
	context "context"
	database "gobooru/internal/database"

	mock "github.com/stretchr/testify/mock"

	models "gobooru/internal/models"
)

// MockPostTagQuery is an autogenerated mock type for the PostTagQuery type
type MockPostTagQuery struct {
	mock.Mock
}

type MockPostTagQuery_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostTagQuery) EXPECT() *MockPostTagQuery_Expecter {
	return &MockPostTagQuery_Expecter{mock: &_m.Mock}
}

// AssociatePosts provides a mock function with given fields: ctx, db, post, tags
func (_m *MockPostTagQuery) AssociatePosts(ctx context.Context, db database.DBClient, post models.Post, tags []models.Tag) error {
	ret := _m.Called(ctx, db, post, tags)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.DBClient, models.Post, []models.Tag) error); ok {
		r0 = rf(ctx, db, post, tags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPostTagQuery_AssociatePosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssociatePosts'
type MockPostTagQuery_AssociatePosts_Call struct {
	*mock.Call
}

// AssociatePosts is a helper method to define mock.On call
//   - ctx context.Context
//   - db database.DBClient
//   - post models.Post
//   - tags []models.Tag
func (_e *MockPostTagQuery_Expecter) AssociatePosts(ctx interface{}, db interface{}, post interface{}, tags interface{}) *MockPostTagQuery_AssociatePosts_Call {
	return &MockPostTagQuery_AssociatePosts_Call{Call: _e.mock.On("AssociatePosts", ctx, db, post, tags)}
}

func (_c *MockPostTagQuery_AssociatePosts_Call) Run(run func(ctx context.Context, db database.DBClient, post models.Post, tags []models.Tag)) *MockPostTagQuery_AssociatePosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.DBClient), args[2].(models.Post), args[3].([]models.Tag))
	})
	return _c
}

func (_c *MockPostTagQuery_AssociatePosts_Call) Return(_a0 error) *MockPostTagQuery_AssociatePosts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPostTagQuery_AssociatePosts_Call) RunAndReturn(run func(context.Context, database.DBClient, models.Post, []models.Tag) error) *MockPostTagQuery_AssociatePosts_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPostTagQuery creates a new instance of MockPostTagQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostTagQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostTagQuery {
	mock := &MockPostTagQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
