// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"
	dtos "gobooru/internal/dtos"

	mock "github.com/stretchr/testify/mock"
)

// MockPoolService is an autogenerated mock type for the PoolService type
type MockPoolService struct {
	mock.Mock
}

type MockPoolService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPoolService) EXPECT() *MockPoolService_Expecter {
	return &MockPoolService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, dto
func (_m *MockPoolService) Create(ctx context.Context, dto dtos.CreatePoolDTO) (dtos.CreatePoolResponseDTO, error) {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 dtos.CreatePoolResponseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dtos.CreatePoolDTO) (dtos.CreatePoolResponseDTO, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dtos.CreatePoolDTO) dtos.CreatePoolResponseDTO); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Get(0).(dtos.CreatePoolResponseDTO)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dtos.CreatePoolDTO) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPoolService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPoolService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - dto dtos.CreatePoolDTO
func (_e *MockPoolService_Expecter) Create(ctx interface{}, dto interface{}) *MockPoolService_Create_Call {
	return &MockPoolService_Create_Call{Call: _e.mock.On("Create", ctx, dto)}
}

func (_c *MockPoolService_Create_Call) Run(run func(ctx context.Context, dto dtos.CreatePoolDTO)) *MockPoolService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dtos.CreatePoolDTO))
	})
	return _c
}

func (_c *MockPoolService_Create_Call) Return(_a0 dtos.CreatePoolResponseDTO, _a1 error) *MockPoolService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPoolService_Create_Call) RunAndReturn(run func(context.Context, dtos.CreatePoolDTO) (dtos.CreatePoolResponseDTO, error)) *MockPoolService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, dto
func (_m *MockPoolService) Delete(ctx context.Context, dto dtos.DeletePoolDTO) (dtos.DeletePoolResponseDTO, error) {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 dtos.DeletePoolResponseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dtos.DeletePoolDTO) (dtos.DeletePoolResponseDTO, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dtos.DeletePoolDTO) dtos.DeletePoolResponseDTO); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Get(0).(dtos.DeletePoolResponseDTO)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dtos.DeletePoolDTO) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPoolService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPoolService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - dto dtos.DeletePoolDTO
func (_e *MockPoolService_Expecter) Delete(ctx interface{}, dto interface{}) *MockPoolService_Delete_Call {
	return &MockPoolService_Delete_Call{Call: _e.mock.On("Delete", ctx, dto)}
}

func (_c *MockPoolService_Delete_Call) Run(run func(ctx context.Context, dto dtos.DeletePoolDTO)) *MockPoolService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dtos.DeletePoolDTO))
	})
	return _c
}

func (_c *MockPoolService_Delete_Call) Return(_a0 dtos.DeletePoolResponseDTO, _a1 error) *MockPoolService_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPoolService_Delete_Call) RunAndReturn(run func(context.Context, dtos.DeletePoolDTO) (dtos.DeletePoolResponseDTO, error)) *MockPoolService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Fetch provides a mock function with given fields: ctx, dto
func (_m *MockPoolService) Fetch(ctx context.Context, dto dtos.FetchPoolDTO) (dtos.FetchPoolResponseDTO, error) {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 dtos.FetchPoolResponseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dtos.FetchPoolDTO) (dtos.FetchPoolResponseDTO, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dtos.FetchPoolDTO) dtos.FetchPoolResponseDTO); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Get(0).(dtos.FetchPoolResponseDTO)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dtos.FetchPoolDTO) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPoolService_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockPoolService_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - dto dtos.FetchPoolDTO
func (_e *MockPoolService_Expecter) Fetch(ctx interface{}, dto interface{}) *MockPoolService_Fetch_Call {
	return &MockPoolService_Fetch_Call{Call: _e.mock.On("Fetch", ctx, dto)}
}

func (_c *MockPoolService_Fetch_Call) Run(run func(ctx context.Context, dto dtos.FetchPoolDTO)) *MockPoolService_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dtos.FetchPoolDTO))
	})
	return _c
}

func (_c *MockPoolService_Fetch_Call) Return(_a0 dtos.FetchPoolResponseDTO, _a1 error) *MockPoolService_Fetch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPoolService_Fetch_Call) RunAndReturn(run func(context.Context, dtos.FetchPoolDTO) (dtos.FetchPoolResponseDTO, error)) *MockPoolService_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, dto
func (_m *MockPoolService) List(ctx context.Context, dto dtos.ListPoolDTO) (dtos.ListPoolResponseDTO, error) {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 dtos.ListPoolResponseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dtos.ListPoolDTO) (dtos.ListPoolResponseDTO, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dtos.ListPoolDTO) dtos.ListPoolResponseDTO); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Get(0).(dtos.ListPoolResponseDTO)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dtos.ListPoolDTO) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPoolService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPoolService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - dto dtos.ListPoolDTO
func (_e *MockPoolService_Expecter) List(ctx interface{}, dto interface{}) *MockPoolService_List_Call {
	return &MockPoolService_List_Call{Call: _e.mock.On("List", ctx, dto)}
}

func (_c *MockPoolService_List_Call) Run(run func(ctx context.Context, dto dtos.ListPoolDTO)) *MockPoolService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dtos.ListPoolDTO))
	})
	return _c
}

func (_c *MockPoolService_List_Call) Return(_a0 dtos.ListPoolResponseDTO, _a1 error) *MockPoolService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPoolService_List_Call) RunAndReturn(run func(context.Context, dtos.ListPoolDTO) (dtos.ListPoolResponseDTO, error)) *MockPoolService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, dto
func (_m *MockPoolService) Update(ctx context.Context, dto dtos.UpdatePoolDTO) (dtos.UpdatePoolResponseDTO, error) {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 dtos.UpdatePoolResponseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dtos.UpdatePoolDTO) (dtos.UpdatePoolResponseDTO, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dtos.UpdatePoolDTO) dtos.UpdatePoolResponseDTO); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Get(0).(dtos.UpdatePoolResponseDTO)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dtos.UpdatePoolDTO) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPoolService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPoolService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - dto dtos.UpdatePoolDTO
func (_e *MockPoolService_Expecter) Update(ctx interface{}, dto interface{}) *MockPoolService_Update_Call {
	return &MockPoolService_Update_Call{Call: _e.mock.On("Update", ctx, dto)}
}

func (_c *MockPoolService_Update_Call) Run(run func(ctx context.Context, dto dtos.UpdatePoolDTO)) *MockPoolService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dtos.UpdatePoolDTO))
	})
	return _c
}

func (_c *MockPoolService_Update_Call) Return(_a0 dtos.UpdatePoolResponseDTO, _a1 error) *MockPoolService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPoolService_Update_Call) RunAndReturn(run func(context.Context, dtos.UpdatePoolDTO) (dtos.UpdatePoolResponseDTO, error)) *MockPoolService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPoolService creates a new instance of MockPoolService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPoolService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPoolService {
	mock := &MockPoolService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
