
version: '3.9'

name: gobooru

# contain all services
services:
  gobooru-server:
    container_name: gobooru-server
    depends_on:
      gobooru-db:
        condition: service_healthy
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: no
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_SSLMODE=${DB_SSLMODE}
      - STATIC_PATH=/app/data
    ports:
      - ${SERVER_PORT}:8080
    user : "1000:1000"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8080/ping || exit 1" ]
      interval: 60s
      timeout: 3s
      retries: 3
    volumes:
      - server-data:/app/data
  gobooru-db:
    container_name: gobooru-db
    image: postgres
    restart: no
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5450:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s  
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  server-data: 
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker-data/server
  db-data: 
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker-data/db