
version: '3.9'

name: gobooru-dev

# contain all services that are needed for development
services:
  gobooru-dev-db:
    container_name: gobooru-dev-db
    image: postgres
    restart: no
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5450:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s  
    volumes:
      - gobooru-dev-db-data:/var/lib/postgresql/data

volumes:
  gobooru-dev-db-data:
