
version: '3.9'

name: gobooru-dev

services:
  gobooru-dev-db:
    container_name: gobooru-dev-db
    image: postgres
    restart: no
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5450:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s  
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
