
version: '3.9'

name: gobooru-dev

services:
  gobooru-dev-db:
    container_name: gobooru-dev-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5450:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
