DROP TABLE "pool_posts" CASCADE;
DROP TABLE "posts" CASCADE;
DROP TABLE "pool" CASCADE;
DROP TABLE "post_tags" CASCADE;
DROP TABLE "tags" CASCADE;
DROP TABLE "post_signatures" CASCADE;
DROP TABLE "post_relations" CASCADE;
DROP TABLE "tag_aliases" CASCADE;
DROP TABLE "tag_implication" CASCADE;