name: tests

on:
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
defaults:
  run:
    working-directory: ./server
      
jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      image: docker
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
          cache-dependency-path: subdir/go.sum
    
      - name: Install dependencies
        run: go mod download
    
      - name: Test
        run: go test ./...
